// Monster data — rediger din egen entry her!
// Fyll inn: name, img (URL eller lokal sti), description, color
// Eksempel: { id: "DRAGON", name: "Smaug", img: "./images/dragon.png", description: "Bryter fjell med ett pust", color: "#8B0000" }

const MONSTERS = [
  { id: "ANGEL",     name: "", img: "", description: "", color: "" },
  { id: "BASILISK",  name: "Basilisken", img: "./images/SHISHAN/basilisk.png", description: "Et blikk og du er toast", color: "#1a4a1a" },
  { id: "BEHEMOTH",  name: "Behemothen", img: "./images/SHISHAN/behemoth.png", description: "Så stor at serveren krasjer av å laste bildet", color: "#3d2b1a" },
  { id: "CENTAUR",   name: "", img: "", description: "", color: "" },
  { id: "CERBERUS",  name: "", img: "", description: "", color: "" },
  { id: "CHIMERA",   name: "", img: "", description: "", color: "" },
  { id: "CYCLOPS",   name: "", img: "", description: "", color: "" },
  { id: "DEMON",     name: "", img: "", description: "", color: "" },
  { id: "DEVIL",     name: "", img: "", description: "", color: "" },
  { id: "DJINN",     name: "Læreren™", img: "./images/SHISHAN/djinn.png", description: "Debugger Eldoria, koser med katter, og kaller sloppy JS for 'pedagogisk'", color: "#1a1a5e" },
  { id: "DRAGON",    name: "", img: "", description: "", color: "" },
  { id: "ELEMENTAL", name: "", img: "", description: "", color: "" },
  { id: "FENRIR",    name: "", img: "", description: "", color: "" },
  { id: "GARGOYLE",  name: "", img: "", description: "", color: "" },
  { id: "GOLEM",     name: "", img: "", description: "", color: "" },
  { id: "GRIFFIN",   name: "", img: "", description: "", color: "" },
  { id: "HARPY",     name: "", img: "", description: "", color: "" },
  { id: "HYDRA",     name: "", img: "", description: "", color: "" },
  { id: "IMP",       name: "", img: "", description: "", color: "" },
  { id: "KITSUNE",   name: "", img: "", description: "", color: "" },
  { id: "KRAKEN",    name: "", img: "", description: "", color: "" },
  { id: "LEVIATHAN", name: "", img: "", description: "", color: "" },
  { id: "LICH",      name: "", img: "", description: "", color: "" },
  { id: "MANTICORE", name: "", img: "", description: "", color: "" },
  { id: "MEDUSA",    name: "", img: "", description: "", color: "" },
  { id: "MINOTAUR",  name: "", img: "", description: "", color: "" },
  { id: "OGRE",      name: "", img: "", description: "", color: "" },
  { id: "ORC",       name: "", img: "", description: "", color: "" },
  { id: "PEGASUS",   name: "", img: "", description: "", color: "" },
  { id: "PHOENIX",   name: "", img: "", description: "", color: "" },
  { id: "SATYR",     name: "", img: "", description: "", color: "" },
  { id: "SHISHAN",   name: "Willow the master", img: "./images/SHISHAN/barberian.png", description: "I am the one and this length of text is ok to have, is that ok yo?", color: "darkred" },
  { id: "SPHINX",    name: "", img: "", description: "", color: "" },
  { id: "TROLL",     name: "", img: "", description: "", color: "" },
  { id: "UNICORN",   name: "", img: "", description: "", color: "" },
  { id: "VAMPIRE",   name: "", img: "", description: "", color: "" },
  { id: "WEREWOLF",  name: "", img: "", description: "", color: "" },
  { id: "WYVERN",    name: "", img: "", description: "", color: "" },
  { id: "YETI",      name: "", img: "", description: "", color: "" },
  { id: "ZOMBIE",    name: "", img: "", description: "", color: "" },
];
